Add NorSand input JSON
cb-geo/mpm-doc pull request #41
Opened 2020-04-27 18:26 UTC by ezrayst

In response to #10

2020-04-27 18:27 UTC, ezrayst commented
An example of input JSON file used is provided. More on the theory would be provided in the future.

2020-04-27 19:36 UTC, kks32 requested changes
I can't see the NorSand, but this adds the random generator which doens't exist yet, could you please fix?

2020-04-27 20:27 UTC, ezrayst commented
Sorry, uploaded the wrong file. Now is fixed!

2020-04-29 04:47 UTC, kks32 approved these changes

2020-04-29 04:48 UTC, merged